### ISSUE TITLE
[BUG]: popup flashes disappears 

### ISSUE THREAD

**Issue by lpanebr** [2KAbhishek/tmux-tea#10]
### Description of the bug

After activating the plugin the popup flashes and disappears as show below:
https://github.com/user-attachments/assets/e32aacc9-8107-4702-8960-437c51187d8e

**I'm using the following versions of the ubuntu, tmux and zoxide:**
```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy

❯ tmux -V
tmux 3.2a

❯ zoxide --version
zoxide v0.4.3-unknown

❯ fzf --version
0.29 (devel)

❯ which tea
/home/lpanebr/.local/bin/tea

❯ ll ~/.local/bin/tea
Permissions Size User    Date Modified Name
lrwxrwxrwx     - lpanebr 25 out 18:32   /home/lpanebr/.local/bin/tea -> /home/lpanebr/.tmux/plugins/tmux-tea/bin/tea.sh
```

**The workaround I found is to strip down the fzf-tmux command as shown below:**
```bash
...
    attached)
        result=$(get_fzf_results | fzf-tmux \
            --no-sort --prompt "$prompt" --preview "$preview" \
            --preview-window=bottom,75% $fzf_tmux_options)
        # --bind "$find_bind" --bind "$session_bind" --bind "$tab_bind" --bind "$window_bind" --bind "$t_bind" \
        # --bind "$zoxide_bind" --bind "$kill_bind" --border-label "$border_label" --header "$header" \
        # --no-sort --prompt "$prompt" --marker "$marker" --preview "$preview" \
        # --preview-window=top,75% $fzf_tmux_options)
        ;;
...
```

### Steps To Reproduce

1. Install as instructed
2. Activate using `Ctrl-t`

**Comment by 2KAbhishek** [comment]
Hey thanks for the notes, I'll take a look, might be a config thing, I'll try to recreate

**Comment by 2KAbhishek** [comment]
@lpanebr do you have `eza` installed? its an ls alternative and is being used for directory previews

another thing I'll recommend checking is if you have set any fzf / fzf_tmux env vars

**Comment by lpanebr** [comment]
@2KAbhishek actually yes, I do have `eza` installed.

As for `fzf` it seems that I only have the `$FZF_DEFAULT_COMMAND` env var defined:

```bash
❯ eza --version
eza - A modern, maintained replacement for ls
v0.18.22 [+git]
https://github.com/eza-community/eza


❯ echo $FZF_DEFAULT_COMMAND
rg --files --hidden --follow --glob '!.git'
```

Sorry, but it was not clear to me if any of that is a problem, and if so, how to fix it. 🤔

Thanks!!!

**Comment by 2KAbhishek** [comment]
@lpanebr from the looks of it, seems like the fzf `--bind` commands are the only ones that are causing problems, also the version you are using `0.29` might not have support for it.

Can you try upgrading fzf to the latest release `0.56` and try this again?

**Comment by 2KAbhishek** [comment]
@lpanebr were you able to try out the suggestion?

**Comment by lpanebr** [comment]
@2KAbhishek sorry for the delay. I've just tested upgrading fzf and if fixed it!

Thanks!!
