### ISSUE TITLE
[ENH]: Making `C-t` optional

### ISSUE THREAD

**Issue by epicmet** [2KAbhishek/tmux-tea#12]
### Description

I'm using `C-t` in my workflow for something else and I would like to use your cool plugin with just `<prefix>t`. Can you make the `C-t` default keybind optional?
https://github.com/2KAbhishek/tmux-tea/blob/25332dc12cce8c71b424f102e649587ac250a187/tea.tmux#L17

**Comment by 2KAbhishek** [comment]
Hey thanks, I will add a config for this
or better yet, if you are interested, why don't you try creating a PR yourself @epicmet 😄

**Comment by epicmet** [comment]
Sure thing, I would like contribute! Though I don't what exactly is on your mind.
We can have a new option for enabling/disabling the default `C-t` binding. Or remove the default binding and in the documentation inform users to pass `C-t` as `@tea-bind` option if they want the same behavior (this option wouldn't be backward compatible).

What would you think is the better option?

**Comment by 2KAbhishek** [comment]
@epicmet thanks for asking, here's what I had in mind:

We can add an option named `tea-alt-bind` with the default value set to "C-t" (that way, it is backwards compatible with existing users configs)

- if the value is an empty string, then the keybinding is not added
- if a non empty string is present, then it is used to add the binding using `tmux bind-key -n`

You can find all the required code for this as part of `tea.tmux`, It'll be great if you can also update the readme to reflect this change.

**Comment by epicmet** [comment]
OK but how can I differentiate between empty string and the absents of `tea-alt-bin` (the null value)? As far as I know they are the same in the context of bash

**Comment by 2KAbhishek** [comment]
@epicmet you are right, let's use "false" for clarity

if `tea-alt-bind` is set to `false` then no binding is aded, else it will use the value of it as the keyboard shortcut

**Comment by 2KAbhishek** [comment]
fixed with #13
