### ISSUE TITLE
[BUG]: Inconsistent UI behavior when sessions have shared prefix in name.

### ISSUE THREAD

**Issue by patrick-motard** [2KAbhishek/tmux-tea#7]
### Description of the bug

Consider 3 project directories:
- ~/foo
- ~/foo-bar
- ~/baz

Each are opened in thier own session using tmux-tea. 
The sessions listed when pressing ctrl-t are different depending on what session you are in.
Sometimes foo is shown as ~/foo and is higher up in the list with other directories. Other times it is foo. Same with foo-bar.

What I expect is when i press ctrl-t, the list i see is the list of sessions i have open in order of last visited, so that I can quickly switch between sessions. When the last visited shares a common prefix in the name, it is not shown as the last visited. This makes it very frustating to switch between the two.

### Steps To Reproduce

See above.

**Comment by 2KAbhishek** [comment]
That's interesting, thanks for reporting it

If you are willing to work on the PR I am more than happy to help.

This probably has to do with the way fzf is sorting the names

**Comment by patrick-motard** [comment]
I will take a crack at it. Thank you for being willing to accept a PR to fix it!
